<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>kp</string>
		<string>cp</string>
		<string>mod</string>
		<string>Mod</string>
	</array>
	<key>keyEquivalent</key>
	<string>^~P</string>
	<key>name</key>
	<string>blackboxcomponentbuilder</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\b(ABSTRACT|ARRAY|BEGIN|BY|CASE|CLOSE|CONST|DIV|ELSE|ELSIF|EMPTY|END|EXIT|EXTENSIBLE|IF|IMPORT|IN|IS|LIMITED|LOOP|MOD|MODULE|NIL|OF|OR|OUT|POINTER|PROCEDURE|RECORD|THEN|TO|TYPE|UNTIL|VAR|WITH)\b</string>
			<key>name</key>
			<string>keyword.blackboxcomponentbuilder</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.prototype.blackboxcomponentbuilder</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.prototype.blackboxcomponentbuilder</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(?i:(function|procedure|constructor|destructor))\b\s+(\w+(\.\w+)?)(\(.*?\))?;\s*(?=(?i:attribute|forward|external))</string>
			<key>name</key>
			<string>meta.function.prototype.blackboxcomponentbuilder</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.function.blackboxcomponentbuilder</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.blackboxcomponentbuilder</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(?i:(function|procedure|constructor|destructor|property|read|write))\b\s+(\w+(\.\w+)?)</string>
			<key>name</key>
			<string>meta.function.blackboxcomponentbuilder</string>
		</dict>
			<dict>
			<key>match</key>
			<string>\b(?i:(self|result))\b</string>
			<key>name</key>			
			<string>token.variable</string>
		</dict>	
		<dict>
			<key>match</key>
			<string>\b(?i:(and|or))\b</string>
			<key>name</key>			
			<string>keyword.operator.blackboxcomponentbuilder</string>
		</dict>	
		<dict>
			<key>match</key>
			<string>\b(WHILE|REPEAT|RETURN|DO|FOR)\b</string>
			<key>name</key>			
			<string>keyword.control.blackboxcomponentbuilder</string>
		</dict>	

		<dict>
			<key>begin</key>
			<string>\{\$</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>string.regexp</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\}</string>
			<key>name</key>
			<string>string.regexp</string>
		</dict>	

		<dict>
			<key>match</key>
			<string>\b(?i:(ansichar|ansistring|boolean|byte|cardinal|char|chajj|comp|currency|double|dword|extended|file|integer|int64|longint|longword|nativeint|nativeuint|olevariant|pansichar|pchar|pwidechar|pointer|real|shortint|shortstring|single|smallint|string|uint64|variant|widechar|widestring|word|wordbool))\b</string>
			<key>name</key>			
			<string>storage.support.type.blackboxcomponentbuilder</string>
		</dict>	
		<dict>
			<key>match</key>
			<string>\b((0(x|X)[0-9a-fA-F]*)|(([0-9]+\.?[0-9]*)|(\.[0-9]+))((e|E)(\+|-)?[0-9]+)?)(L|l|UL|ul|u|U|F|f|ll|LL|ull|ULL)?\b</string>
			<key>name</key>
			<string>constant.numeric.blackboxcomponentbuilder</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\$[0-9a-fA-F]{1,16}\b</string>
			<key>name</key>
			<string>constant.numeric.blackboxcomponentbuilder</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:(true|false|nil))\b</string>
			<key>name</key>
			<string>constant.language.blackboxcomponentbuilder</string>
		</dict>
	
		<dict>
			<key>include</key>
			<string>#multilinecomment</string>
		</dict>
	
		<dict>
			<key>applyEndPatternLast</key>
			<integer>1</integer>
			<key>begin</key>
			<string>'</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.blackboxcomponentbuilder</string>
				</dict>
			</dict>
			<key>end</key>
			<string>'</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.blackboxcomponentbuilder</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.single.blackboxcomponentbuilder</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>''</string>
					<key>name</key>
					<string>constant.character.escape.apostrophe.blackboxcomponentbuilder</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>applyEndPatternLast</key>
			<integer>1</integer>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.blackboxcomponentbuilder</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.blackboxcomponentbuilder</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.single.blackboxcomponentbuilder</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>""</string>
					<key>name</key>
					<string>constant.character.escape.apostrophe.blackboxcomponentbuilder</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>multilinecomment</key>
		<dict>
			<key>begin</key>
			<string>\(\*</string>
			<key>contentName</key>
			<string>comment</string>
			<key>end</key>
			<string>\*\)</string>
			<key>name</key>
			<string>comment</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#multilinecomment</string>
					<key>name</key>
					<string>comment</string>
				</dict>
			</array>
		</dict>
	</dict>	
	<key>scopeName</key>
	<string>source.blackboxcomponentbuilder</string>
	<key>uuid</key>
	<string>F42FA544-6B1C-11D9-9517-000D93589AF6</string>
</dict>
</plist>
